<?php
/*
* Version 0.1
*/

if( function_exists('acf_add_local_field_group') && $_SERVER['SERVER_NAME'] != 'perf.dev' ):

	acf_add_local_field_group(array (
		'key' => 'group_56055ca795f6f',
		'title' => 'Perfthemes general options',
		'fields' => array (
			array (
				'key' => 'field_56055cee1dad1',
				'label' => 'General',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_56055d391dad5',
				'label' => 'Boxed layout ?',
				'name' => 'boxed_layout',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_560961fa510ed',
				'label' => 'Your logo',
				'name' => 'your_logo',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_564e3afc7a5f1',
				'label' => 'Typography',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_564e3b277a5f2',
				'label' => 'Use Google Font',
				'name' => 'use_google_font',
				'type' => 'true_false',
				'instructions' => 'By default, this theme use <a href="https://medium.com/@mwichary/system-shock-6b1dc6d6596f#.dtui0ww6r" target="_blank">System fonts</a> for faster performance. If for whatever reason you prefer to use Google Font, select this box and choose your fallback Google Font.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_564e3b437a5f3',
				'label' => 'Google font',
				'name' => 'google_font',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_564e3b277a5f2',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'open-sans' => 'Open Sans',
					'lato' => 'Lato',
				),
				'default_value' => array (
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'perfthemes-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_56438a07179d1',
		'title' => 'Perfthemes performances',
		'fields' => array (
			array (
				'key' => 'field_56438a071a01f',
				'label' => 'JavaScript Optimisation',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_564f4063bb746',
				'label' => 'Disable JavaScript optimisation',
				'name' => 'perf_disable_js_optimisation',
				'type' => 'checkbox',
				'instructions' => '<p>By disabling one of those options, you will affect negatively your <a href="https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index" target="_blank">Speed Index</a>.</p>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'disable_js_auto_async' => 'Disable auto loading scripts asynchronously',
				),
				'default_value' => array (
				),
				'layout' => 'vertical',
				'toggle' => 0,
			),
			array (
				'key' => 'field_56438a071a12f',
				'label' => 'Manually select script to load asynchronously',
				'name' => 'perf_manual_async_js',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_564f4063bb746',
							'operator' => '==',
							'value' => 'disable_js_auto_async',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'layout' => 'table',
				'button_label' => 'Add a new script',
				'sub_fields' => array (
					array (
						'key' => 'field_56438a07242fd',
						'label' => 'Scripts to add',
						'name' => 'perf_add_asset',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
			array (
				'key' => 'field_564b2c400f1fe',
				'label' => 'What are you doing exactly?',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'If you want to know more about Removing Render-Blocking JavaScript, please visit <a href="https://developers.google.com/speed/docs/insights/BlockingJS" target="_blank">Google Developpers page</a>',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_564a00dd8aee9',
				'label' => 'CSS Optimisation',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_564f29ab4cded',
				'label' => 'Disable CSS optimisation',
				'name' => 'perf_disable_css_optimisation',
				'type' => 'checkbox',
				'instructions' => '<p>By disabling one of those options, you will affect negatively your <a href="https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index" target="_blank">Speed Index</a>.</p>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'disable_theme_critical_css' => 'Disable theme Critical CSS',
					'disable_css_auto_async' => 'Disable auto loading stylesheet asynchronously',
				),
				'default_value' => array (
				),
				'layout' => 'vertical',
				'toggle' => 0,
			),
			array (
				'key' => 'field_564a01868aeec',
				'label' => 'Manually select styelsheet to load asynchronously',
				'name' => 'perf_manual_async_stylesheets',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_564f29ab4cded',
							'operator' => '==',
							'value' => 'disable_css_auto_async',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'layout' => 'table',
				'button_label' => 'Add stylesheet',
				'sub_fields' => array (
					array (
						'key' => 'field_564a01868aeed',
						'label' => 'Stylesheets to load async',
						'name' => 'perf_add_asset',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
			array (
				'key' => 'field_564b2c240f1fd',
				'label' => 'What are you doing exactly?',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'If you want to know more about CSS Delivery Optimisation, please visit <a href="https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery" target="_blank">Google Developpers page</a>',
				'esc_html' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-performance',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_56438a0516bb9',
		'title' => 'Perfthemes styles',
		'fields' => array (
			array (
				'key' => 'field_56438a051ad53',
				'label' => 'Style',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_56438a051add3',
				'label' => 'Main site color',
				'name' => 'perf_main_site_color',
				'type' => 'radio',
				'instructions' => 'Color description: <a href="https://flatuicolors.com/" target="_blank">https://flatuicolors.com/</a>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'#1abc9c' => '<span style="background-color: #1abc9c; display: inline-block; width: 15px; height: 15px;"></span> Turquoise',
					'#2ecc71' => '<span style="background-color: #2ecc71; display: inline-block; width: 15px; height: 15px;"></span> Peter-river',
					'#3498db' => '<span style="background-color: #3498db; display: inline-block; width: 15px; height: 15px;"></span> Wet-asphalt',
					'#16a085' => '<span style="background-color: #16a085; display: inline-block; width: 15px; height: 15px;"></span> Nephritis',
					'#27ae60' => '<span style="background-color: #27ae60; display: inline-block; width: 15px; height: 15px;"></span> Belize-hole',
					'#2980b9' => '<span style="background-color: #2980b9; display: inline-block; width: 15px; height: 15px;"></span> Midnight-blue',
					'#f1c40f' => '<span style="background-color: #f1c40f; display: inline-block; width: 15px; height: 15px;"></span> Sun-flower',
					'#e67e22' => '<span style="background-color: #e67e22; display: inline-block; width: 15px; height: 15px;"></span> Alizarin',
					'#e74c3c' => '<span style="background-color: #e74c3c; display: inline-block; width: 15px; height: 15px;"></span> Concrete',
					'#f39c12' => '<span style="background-color: #f39c12; display: inline-block; width: 15px; height: 15px;"></span> Orange',
					'#d35400' => '<span style="background-color: #d35400; display: inline-block; width: 15px; height: 15px;"></span> Pomegranate',
					'#c0392b' => '<span style="background-color: #c0392b; display: inline-block; width: 15px; height: 15px;"></span> Asbestos',
					'other' => 'Other',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_56438a051ae52',
				'label' => 'Custom color',
				'name' => 'perf_custom_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_56438a051add3',
							'operator' => '==',
							'value' => 'other',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array (
				'key' => 'field_56438a051aed8',
				'label' => 'Custom CSS styles',
				'name' => 'perf_custom_css_styles',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-styles',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
endif;